Back/README.md

Docs: README.md 파일 추가

---

README.md

Docs: README 추가

---

Back/app/controllers/socketio.controller.js:Zone.Identifier
Back/app/controllers/user.controller.js:Zone.Identifier
Back/app/middlewares/validators.js:Zone.Identifier
Back/app/models/UserInfo.js:Zone.Identifier
Back/app/models/UserLogs.js:Zone.Identifier
Back/app/routes/user.api.routes.js:Zone.Identifier
Back/config/env/development.js:Zone.Identifier
Back/config/env/production.js:Zone.Identifier
Back/config/express_config.js:Zone.Identifier
Back/config/mongoose_config.js:Zone.Identifier
Back/config/node_config.js:Zone.Identifier
Back/config/passport/strategies/user.js:Zone.Identifier
Back/config/passport/user_passport.js:Zone.Identifier
Back/config/routes_config.js:Zone.Identifier
Back/config/socketio.js:Zone.Identifier
Back/package-lock.json:Zone.Identifier
Back/package.json:Zone.Identifier
Back/server.js:Zone.Identifier

Back 폴더 내부 Zone.identifier 파일들 다 삭제

 Fix(BE): Zone.identifier 파일 삭제

---

README.md

README.md 파일 스코프 관련 수정 및 내용 추가

Docs: README.md 파일 스코프 관련 수정 및 내용 추가

---

Front/package-lock.json
Front/package.json
Front/src/main.js
Front/src/store/index.js

Establish(FE): pinia 초기 세팅 완료

---

Front/src/components/UI/BaseButton.vue
Front/src/components/layout/TheHeader.vue
Front/src/main.js
Front/src/pages/bookmark.vue
Front/src/pages/log.vue
Front/src/pages/login.vue
Front/src/pages/main.vue
Front/src/router/index.js

웹페이지 헤더 구현을 위해 pages 폴더에 기본 구조를 가진 컴포넌트를 생성했으며, 라우터로 연결하였습니다. 
버튼 디자인 구현을 위해 UI 폴더를 만들었고, base-button 컴포넌트를 UI로 이용할 수 있게 만들었습니다.

Feat(FE): 웹페이지 헤더 구현

---

Front/src/components/UI/BaseButton.vue
Front/src/components/UI/BaseCard.vue
Front/src/main.js
Front/src/pages/bookmark.vue
Front/src/pages/log.vue
Front/src/pages/login.vue
Front/src/pages/main.vue
Front/src/pages/result.vue
Front/src/router/index.js
Front/src/store/index.js
Front/src/style.css

1. 메인페이지 구성
3. pinia 연결
4. 라우터 연결
main.vue 구성 완료했으며, 입력 텍스트를 저장하기 위해 pinia 연결하였습니다. 
제출하기 버튼 클릭시 result페이지로 넘어가도록 만들었습니다.

FE 메인페이지 구현

---

Back/app/controllers/bookmark.controller.js
Back/app/controllers/user.controller.js
Back/app/middlewares/auth.middleware.js
Back/app/models/Bookmark.js
Back/app/routes/user.api.routes.js
Back/config/express_config.js
Back/config/mongoose_config.js
Back/config/routes_config.js
Back/package-lock.json

북마크 관련 기능으로 
1. 북마크 추가/제거
2. 북마크 목록 조회
3. 북마크 상세 조회 
기능 구현했습니다
3. 북마크 상세 조회에서는 북마크된 이미지와 검색에 사용된 텍스트, 검색 날짜가 응답으로 옵니다.

Feat: BE 북마크 관련 기능 구현

---

Front/src/components/component/LogData.vue
Front/src/pages/log.vue
Front/src/pages/main.vue
Front/src/store/index.js

feat(FE): 검색기록 페이지 기본 구성 완료

---

Front/src/components/component/ImageData.vue
Front/src/pages/bookmark.vue
Front/src/pages/result.vue
Front/src/store/index.js

feat(FE): 북마크 페이지 기본 구성 완료

---

Front/src/pages/login.vue
Front/src/pages/signup.vue
Front/src/router/index.js
Front/src/store/index.js

로그인 페이지, 회원가입 페이지 기본 구성 완료했습니다. 
추가적으로 디자인이 필요합니다.

FE 로그인 페이지, 회원가입 페이지 기본 구성

---

Front/src/components/component/ImageData.vue
Front/src/components/component/ImageModal.vue
Front/src/components/component/LogData.vue
Front/src/components/component/LogModal.vue
Front/src/pages/bookmark.vue
Front/src/pages/log.vue
Front/src/store/index.js

FE 상세보기 기능 구현

---

Front/src/composables/useAxios.js
Front/src/composables/useSocket.js
Front/src/main.js
Front/src/pages/login.vue
Front/src/plugins/axios.js
Front/src/plugins/socket.js
Front/src/store/socket.js

회의 후 통신 기능 구현을 위한 socket 파일이 추가되었습니다.

feat(FE): 회의 후 변경 부분 반영

---

Back/app/controllers/bookmark.controller.js
Back/app/controllers/search.controller.js
Back/app/controllers/searchHistory.controller.js
Back/app/controllers/user.controller.js
Back/app/middlewares/auth.middleware.js
Back/app/routes/user.api.routes.js
Back/server.js

Feat : 검색 기록 관련 기능 구현

---

Back/app/controllers/socketio.controller.js
Back/config/socketio.js

토큰이 없을 때는 제한된 접근으로 socket/io 연결이 가능하도록
로그인 후 token 을 보내면 그 때부터 search 기능을 socket io 로 사용할 수 있도록 재연결

Fix: BE sokcet io 관련 연결 메커니즘 수정

---

Back/config/express_config.js

BE의 이미지 get 요청에 대한 CORS 에러에 
이미지 파일을 제공하는 정적 경로에 대한 CORS 설정이 안돼있음을 확인 후 
CORS 설정 추가

Fix:BE 이미지 get 요청에 대한 CORS 에러 수정

---

Back/app/controllers/searchHistory.controller.js

BE 검색 기록 상세 조회 시 북마크 여부 확인 기능 추가
검색 기록 상세 조회 응답 예시
{
"date": "2024. 12. 01.",
"text": "test_txt",
"originalImage": {
"url": "/uploads/original/1733053188613-original-2024-09-20 020221.png",
"isBookmarked": false
},
"results": [
{
"url": "/uploads/results/1733053188614-result1-2024-09-20 020221.png",
"isBookmarked": true
},
{
"url": "/uploads/results/1733053188616-result2-2024-09-20 020221.png",
"isBookmarked": false
},
{
"url": "/uploads/results/1733053188618-result3-2024-09-20 020221.png",
"isBookmarked": false
}
]
}

Fix:BE 검색 기록 상세 조회 시 북마크 여부 확인 기능 추가

---

Front/src/components/LogModal.vue
Front/src/pages/log.vue

fix: 로그 상세보기에서 북마크 삭제 기능 수정

---

Front/src/layout/TheHeader.vue
Front/src/pages/main.vue
Front/src/pages/result.vue
Front/src/store/results.js

FE 로그인 헤더, 결과 페이지 이미지 결과 수정 완료

FE 로그인 헤더, 결과 페이지 이미지 결과 수정

---

Front/src/pages/bookmark.vue
Front/src/pages/log.vue
Front/src/store/images.js
Front/src/store/logs.js

FE 검색 기록 페이지, 북마크 페이지 페이지 기능 구현 완료

FE 검색 기록 페이지, 북마크 페이지 페이지 기능 구현

---

Front/src/components/ImageData.vue
Front/src/components/ImageModal.vue
Front/src/pages/bookmark.vue
Front/src/store/images.js
Front/src/store/logs.js

fix: 북마크 버튼을 모달에서만 누를 수 있게 수정 완료

fix: 북마크 버튼을 모달에서만 누를 수 있게 수정

---

Front/src/pages/main.vue

이미지 업로드 시 결과 업로드 화면 아래에 보여주도록 수정하여 문제 해결

FE 이미지 업로드 시 결과 업로드 화면 아래에 보여주도록 수정

---

Front/src/layout/TheHeader.vue
Front/src/pages/bookmark.vue
Front/src/pages/log.vue
Front/src/store/images.js
Front/src/store/logs.js

FE 새로고침시 1페이지로 무조건 돌아가는 현상 수정

---

Front/src/components/LoadingSpinner.vue
Front/src/pages/main.vue

feat: 로딩 스피너 추가
